# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(387, 249)
        MainWindow.setMinimumSize(QtCore.QSize(387, 249))
        MainWindow.setMaximumSize(QtCore.QSize(387, 249))
        MainWindow.setAutoFillBackground(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 381, 25))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        self.closeButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        self.closeButton.setFont(font)
        self.closeButton.setObjectName("closeButton")
        self.horizontalLayout_2.addWidget(self.closeButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.moreButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setBold(False)
        font.setWeight(50)
        self.moreButton.setFont(font)
        self.moreButton.setObjectName("moreButton")
        self.horizontalLayout_2.addWidget(self.moreButton)
        self.lcdNumber = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber.setGeometry(QtCore.QRect(230, 20, 151, 31))
        self.lcdNumber.setObjectName("lcdNumber")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(230, 50, 151, 170))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_n1 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_n1.setObjectName("pushButton_n1")
        self.gridLayout.addWidget(self.pushButton_n1, 3, 0, 1, 1)
        self.pushButton_n9 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_n9.setObjectName("pushButton_n9")
        self.gridLayout.addWidget(self.pushButton_n9, 1, 2, 1, 1)
        self.pushButton_n4 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_n4.setObjectName("pushButton_n4")
        self.gridLayout.addWidget(self.pushButton_n4, 2, 0, 1, 1)
        self.pushButton_cvad = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_cvad.setObjectName("pushButton_cvad")
        self.gridLayout.addWidget(self.pushButton_cvad, 0, 2, 1, 1)
        self.pushButton_n8 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_n8.setObjectName("pushButton_n8")
        self.gridLayout.addWidget(self.pushButton_n8, 1, 1, 1, 1)
        self.pushButton_n7 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_n7.setObjectName("pushButton_n7")
        self.gridLayout.addWidget(self.pushButton_n7, 1, 0, 1, 1)
        self.pushButton_n3 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_n3.setObjectName("pushButton_n3")
        self.gridLayout.addWidget(self.pushButton_n3, 3, 2, 1, 1)
        self.pushButton_cor = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_cor.setObjectName("pushButton_cor")
        self.gridLayout.addWidget(self.pushButton_cor, 0, 3, 1, 1)
        self.pushButton_add = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_add.setObjectName("pushButton_add")
        self.gridLayout.addWidget(self.pushButton_add, 1, 3, 1, 1)
        self.pushButton_n2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_n2.setObjectName("pushButton_n2")
        self.gridLayout.addWidget(self.pushButton_n2, 3, 1, 1, 1)
        self.pushButton_n6 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_n6.setObjectName("pushButton_n6")
        self.gridLayout.addWidget(self.pushButton_n6, 2, 2, 1, 1)
        self.pushButton_mul = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_mul.setObjectName("pushButton_mul")
        self.gridLayout.addWidget(self.pushButton_mul, 3, 3, 1, 1)
        self.pushButton_div = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_div.setObjectName("pushButton_div")
        self.gridLayout.addWidget(self.pushButton_div, 4, 3, 1, 1)
        self.pushButton_sub = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_sub.setObjectName("pushButton_sub")
        self.gridLayout.addWidget(self.pushButton_sub, 2, 3, 1, 1)
        self.pushButton_n0 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_n0.setObjectName("pushButton_n0")
        self.gridLayout.addWidget(self.pushButton_n0, 4, 0, 1, 3)
        self.pushButton_n5 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_n5.setObjectName("pushButton_n5")
        self.gridLayout.addWidget(self.pushButton_n5, 2, 1, 1, 1)
        self.pushButton_ac = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_ac.setObjectName("pushButton_ac")
        self.gridLayout.addWidget(self.pushButton_ac, 0, 0, 1, 2)
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(0, 50, 221, 191))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.textEdit.setFont(font)
        self.textEdit.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textEdit.setFrameShadow(QtWidgets.QFrame.Plain)
        self.textEdit.setLineWidth(0)
        self.textEdit.setObjectName("textEdit")
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(0, 20, 231, 31))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(9)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(9)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(9)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.pushButton_eq = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_eq.setGeometry(QtCore.QRect(230, 216, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_eq.setFont(font)
        self.pushButton_eq.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.pushButton_eq.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_eq.setAutoFillBackground(False)
        self.pushButton_eq.setCheckable(False)
        self.pushButton_eq.setAutoRepeat(False)
        self.pushButton_eq.setAutoExclusive(False)
        self.pushButton_eq.setAutoDefault(False)
        self.pushButton_eq.setDefault(False)
        self.pushButton_eq.setFlat(False)
        self.pushButton_eq.setObjectName("pushButton_eq")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Tool"))
        self.closeButton.setText(_translate("MainWindow", "close"))
        self.moreButton.setText(_translate("MainWindow", "add new"))
        self.pushButton_n1.setText(_translate("MainWindow", "1"))
        self.pushButton_n9.setText(_translate("MainWindow", "9"))
        self.pushButton_n4.setText(_translate("MainWindow", "4"))
        self.pushButton_cvad.setText(_translate("MainWindow", "x²"))
        self.pushButton_n8.setText(_translate("MainWindow", "8"))
        self.pushButton_n7.setText(_translate("MainWindow", "7"))
        self.pushButton_n3.setText(_translate("MainWindow", "3"))
        self.pushButton_cor.setText(_translate("MainWindow", "√"))
        self.pushButton_add.setText(_translate("MainWindow", "+"))
        self.pushButton_n2.setText(_translate("MainWindow", "2"))
        self.pushButton_n6.setText(_translate("MainWindow", "6"))
        self.pushButton_mul.setText(_translate("MainWindow", "*"))
        self.pushButton_div.setText(_translate("MainWindow", "÷"))
        self.pushButton_sub.setText(_translate("MainWindow", "-"))
        self.pushButton_n0.setText(_translate("MainWindow", "0"))
        self.pushButton_n5.setText(_translate("MainWindow", "5"))
        self.pushButton_ac.setText(_translate("MainWindow", "del"))
        self.label_3.setText(_translate("MainWindow", "  Date:          "))
        self.label_2.setText(_translate("MainWindow", "Time:     "))
        self.label.setText(_translate("MainWindow", "55    €     "))
        self.pushButton_eq.setText(_translate("MainWindow", "="))

